### ISSUE TITLE
Wheres the API?

### ISSUE THREAD

**Issue by JacobFV** [albanie/samuel-api#1]
Hi Samuel. I was looking for your API endpoint, but I couldn't find it. Do you have like a python library that I can use? I'm ready for the beta.

**Comment by JacobFV** [comment]
I'm not joking. We have an automatic escalation system for failed prompts. It goes gpt4all -> gpt-3.5-turbo -> gpt-4 and Id like to put you as a last resort layer

**Comment by albanie** [comment]
Text queries can be submitted here via [this google form](https://docs.google.com/forms/d/1MeGK6nHwxOFpb9297CktWX9yOjFUgfSQaq8GCOATM9c).
This is linked on: [samuel-api.com](https://samuel-api.com/), though perhaps not very clearly.
I haven't yet set up a Python API (but it should be possible to wrap Google form submissions with Python). 
Lmk if you have difficulties.

**Comment by albanie** [comment]
Closing for now, but feel free to re-open if needed.
